# ~/.config/starship.toml

add_newline = true

# ãƒ•ã‚¡ã‚¤ãƒ«ã‚’ã‚¹ã‚­ãƒ£ãƒ³ã™ã‚‹éš›ã®ã‚¿ã‚¤ãƒ ã‚¢ã‚¦ãƒˆæ™‚é–“
scan_timeout = 10

# ãƒ‘ã‚¹ã®è¡¨ç¤ºè¨­å®š
[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 4
truncate_to_repo = false
truncation_symbol = "â€¦/"

# è¨˜å·ã®è¨­å®š
[character]
success_symbol = "[\\(  Â´âˆ€ï½€\\)](dimmed green)" # ã‚³ãƒãƒ³ãƒ‰æˆåŠŸæ™‚
error_symbol = "[\\( ;Â´Ğ”ï½€\\)](dimmed red)"    # ã‚³ãƒãƒ³ãƒ‰å¤±æ•—æ™‚

[docker_context]
format = 'via [ğŸ‹ $context](blue bold)'
